pulse <- read.table("Pulse.txt", header = TRUE)
pulse <- data.frame(pulse)
summary(pulse$pulse1)
summary(pulse)
mean(pulse$pulse1)
median(pulse$pulse1)
mode(pulse$pulse1)
min(pulse$pulse1)
max(pulse$pulse1)
mean(pulse$pulse2)
median(pulse$pulse2)
min(pulse$pulse2)
max(pulse$pulse2)
summary(pulse$pulse2[pulse$ran == 1])
summary(pulse$pulse2[pulse$ran == 2])
hist(pulse$pulse1)
hist(pulse$pulse2)
hist(pulse$pulse2, xlab = "Pulse", main = "Histogram of Pulse Rate")
hist(pulse$pulse1, xlab = "Pulse", main = "Histogram of Pulse Rate")
pulse
hist(pulse$weight[pulse$sex==2])
hist(pulse$weight[pulse$sex==2], xlab = "weight", main = "Histogram of weights of Female volunteers")
barplot(table(pulse$sex))
barplot(table(pulse$sex), xlab = "men = 1, women = 2", ylab = "frequency", main = "barchart of amount of men vs women in study")
boxplot(pulse$pulse1, pulse$pulse2, names=colnames(pulse)[1:2])
boxplot(pulse$pulse1, pulse$pulse2, names=colnames(pulse)[1:2],xlab = "pulse. before exercise = 1, after exercise = 2", ylab = "frequency", main = "boxplot of pulse before and after exercise")
